### ISSUE TITLE
Telephone number remains public

### ISSUE THREAD

**Issue by SBroomhead** [Acfee/ehna-dev#36]
@getwes  in my personal profile, my telephone number is public. I've tried clicking the box "Keep my number private" but even though I save that, when I refresh the number is still public.

**Comment by getwes** [comment]
I have fixed this bug. "Keep my number private" now sets the db value to private and it doesn't show on the user profile.

**Comment by SBroomhead** [comment]
@getwes it's not fixed yet. I suspect the bug exists because there is not "Update" button for that section, but only at the bottom of the page for the Social content.
Also, my email is private even though the "Keep email private" button is not ticked. This could be a related issue.

**Comment by getwes** [comment]
@SBroomhead its not affected by the update button. once its added. its saved
